// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhscxOmYyJv0Z7YMVTP7vjHSIfmKvnIY',
    appId: '1:415908129222:web:81541f05857f8e7c50aac7',
    messagingSenderId: '415908129222',
    projectId: 'mppo-app',
    authDomain: 'mppo-app.firebaseapp.com',
    storageBucket: 'mppo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAw5pRVY5fKnNTOQitrOqEnlUJEz3dquc',
    appId: '1:415908129222:android:853858b0e9e65c7650aac7',
    messagingSenderId: '415908129222',
    projectId: 'mppo-app',
    storageBucket: 'mppo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVduQUQsD65xozwyUhkU_ySLEt0WwBRg4',
    appId: '1:415908129222:ios:6d92ec7525b9f14c50aac7',
    messagingSenderId: '415908129222',
    projectId: 'mppo-app',
    storageBucket: 'mppo-app.firebasestorage.app',
    iosBundleId: 'com.example.mppoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVduQUQsD65xozwyUhkU_ySLEt0WwBRg4',
    appId: '1:415908129222:ios:6d92ec7525b9f14c50aac7',
    messagingSenderId: '415908129222',
    projectId: 'mppo-app',
    storageBucket: 'mppo-app.firebasestorage.app',
    iosBundleId: 'com.example.mppoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEhscxOmYyJv0Z7YMVTP7vjHSIfmKvnIY',
    appId: '1:415908129222:web:f627c2e188fc809850aac7',
    messagingSenderId: '415908129222',
    projectId: 'mppo-app',
    authDomain: 'mppo-app.firebaseapp.com',
    storageBucket: 'mppo-app.firebasestorage.app',
  );
}
